name: alkitab
description: "Quran before you sleep"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
# ----------------------
environment:
  sdk: ^3.5.4
# ------------------------------------
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  # ------------------------------------
  quran_flutter: ^1.0.2
  provider: ^6.1.2
  flutter_native_splash: ^2.4.1
  share_plus: ^10.0.2
  universal_html: ^2.2.4
  flutter_keyboard_visibility: ^6.0.0
  # ------------------------------------
  basics:
    # ----------------
    # IOS
    # path: /Users/rageh/projects/bldrs/basics
    # ----------------
    # ANDROID
    # path: D:/projects/bldrs_packs/basics
    # ----------------
    # GIT
    git:
      url: https://github.com/RagehAz/basics.git
  # ------------------------------------
  fire:
    # ----------------
    # IOS
    # path: /Users/rageh/projects/bldrs/fire
    # ----------------
    # ANDROID
    # path: D:/projects/bldrs_packs/fire
    # ----------------
    # GIT
    git:
      url: https://github.com/RagehAz/fire.git
  # ------------------------------------
  bldrs:
    # ----------------
    # IOS
    #    path: /Users/rageh/projects/bldrs/bldrs_app
    # ----------------
    # ANDROID
    path: D:/projects/bldrs_packs/bldrs_app
  # ----------------
  # GIT
  #      git:
  #        url: https://github.com/RagehAz/bldrs_app.git
  # --------------------------------------------------------------------------------
dependency_overrides:
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  # ------------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/
  #    - assets/countries/
  #    - assets/aw/
  #    - assets/icons/
  #    - assets/icons/keywords/
  #    - assets/icons/specs/
  #    - assets/icons/flags/
  #    - assets/languages/
  #    - assets/planet/
  #    - assets/sounds/
  # ------------------------------------