name: alkitab
description: "Quran before you sleep"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0
# ----------------------
environment:
  sdk: ^3.5.4
# ----------------------
dependencies:
  flutter:
    sdk: flutter
  # ------------------------------------
  quran: ^1.3.3
  provider: ^6.1.2
  flutter_native_splash: ^2.4.1
  share_plus: ^10.0.2
  # ------------------------------------
  basics:
    # ----------------
    # IOS
    # path: /Users/rageh/projects/bldrs/basics
    # ----------------
    # ANDROID
    # path: D:/projects/bldrs_packs/basics
    # ----------------
    # GIT
    git:
      url: https://github.com/RagehAz/basics.git
  # ------------------------------------
dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^2.1.2
  # ------------------------------------
flutter:
  uses-material-design: true
  assets:
    - assets/
  #    - assets/countries/
  #    - assets/aw/
  #    - assets/icons/
  #    - assets/icons/keywords/
  #    - assets/icons/specs/
  #    - assets/icons/flags/
  #    - assets/languages/
  #    - assets/planet/
  #    - assets/sounds/
  # ------------------------------------