library alkitab_engine;

import 'dart:async';
import 'package:alkitab/alkitab_keys.dart';
import 'package:alkitab/c_protocols/a_bldrs_engine/src/z_clean_slate_protocol.dart';
import 'package:alkitab/d_backend/d_ldb/ldb_doc.dart';
import 'package:alkitab/f_helpers/standards.dart';
import 'package:alkitab/firebase_options.dart';
import 'package:alkitab/main.dart';
import 'package:basics/helpers/checks/device_checker.dart';
import 'package:basics/helpers/checks/tracers.dart';
import 'package:basics/mediator/sounder/sounder.dart';
import 'package:bldrs/c_protocols/main_providers/home_pro.dart';
import 'package:bldrs/c_protocols/main_providers/ui_provider.dart';
import 'package:bldrs/c_protocols/user_protocols/user/user_pro.dart';
import 'package:bldrs/f_helpers/localization/localizer.dart';
import 'package:bldrs/h_navigation/routing/routing.dart';
import 'package:bldrs/z_components/dialogs/dialogz/dialogs.dart';
import 'package:bldrs/z_components/texting/super_verse/verse_model.dart';
import 'package:fire/super_fire.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/foundation.dart';
import 'package:flutter/material.dart';
import 'package:flutter_native_splash/flutter_native_splash.dart';
import 'package:basics/ldb/ldb.dart';
import 'package:basics/helpers/nums/numeric.dart';
import 'package:basics/helpers/time/timers.dart';
import 'package:quran_flutter/quran_flutter.dart' as quran;

part 'src/a_engine.dart';
part 'src/c_ui_initializer.dart';
part 'src/f_the_last_wipe.dart';
